FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# AORTA Rest

Aorta Rest is a simple API allowing tasks to be routed and medical messages to be transferred.

Basic list of the list of services:
 - Task Request (Initiator / Requester of a Task) - Task Management Application
   - Create a Task Request               POST   https://aorta:443/api/tasks
   - Delete a Task Request               DELETE https://aorta:443/api/tasks/123456
   - Update a Task Request               PUT    https://aorta:443/api/tasks/123456

 - Patients
   - Create a Patient                    POST  https://aorta:443/api/patients
   - Update a Patient                    PUT   https://aorta:443/api/patients/123456

 - Patient Admissions
   - Create an Admission                 POST  https://aorta:443/api/patients/123456/admissions
   - Update an Admission                 PUT   https://aorta:443/api/patients/123456/admissions/456789

 - Patient Transfers (Pending or Actual)
   - Create a Transfer                   POST  https://aorta:443/api/patients/123456/transfers
   - Update a Transfer                   PUT   https://aorta:443/api/patients/123456/transfers/789123

 - Hospital Structure
    - Update a Hospital Structure        PUT    https://aorta:443/api/structure

 - Stock
    - Create a Stock Movement Request    POST   https://aorta:443/api/stocks
    - Update a Stock Movement Request    PUT    https://aorta:443/api/stocks/456123
 
 - Appointment
   - Create an Appointment               POST   https://aorta:443/api/patients/123456/appointments
   - Delete an Appointment               DELETE https://aorta:443/api/patients/123456/appointments/789123
   - Update an Appointment               PUT    https://aorta:443/api/patients/123456/appointments/789123

 - Tasks (
   - Create a Task                       POST   https://aorta:443/api/tasks
   - Delete a Task                       DELETE https://aorta:443/api/tasks/123456
   - Update a Task                       PUT    https://aorta:443/api/tasks/123456


## Task Requests Collection [/api/taskrequests]

## Patients Collection [/api/patients]

## Patient Admissions Collection [/api/admissions]

## Patient Transfers Collection [/api/questions]

### Create a Transfer [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {"AortaOutMB":
        {
            "AortaOut_Message_ID":"285e708f-a418-4f2a-8df9-eab236d653eb",
            "AortaOut_Sent_TS":"20160223.122231.780",
            "AortaOut_MessageVersion":"1.0.0.1",
            "AortaOut_MessageType":"HL7_Sourced",
            "AortaRouting_Version":"1.0.0.1",
            "AortaRouting_Ready_TS":"20160223.122231.560",
            "AortaRouting_Info": {},
            "AortaIn_Message_ID":"2f12d80d-ceff-426f-9d2c-6d388670f5b2"
        },
        "HL7_Sourced":
        {
            "MessageType": "OAZIS_HL7_ADT",
            "MessageDetail": "PendingAdmit",
            "HL7_MSH": {
                "HL7_SendingApplication": "OAZIS",
                "HL7_MessageType": "ADT^A14",
                "HL7_ControlID": "00973474",
                "HL7_MessageTS": "20160223122230"
            },
            "Contact_ID": "1600181682",
            "Patient": {
                "PatientHospitalID": "0059613",
                "PatientLastName": "Familienaam",
                "PatientFirstName": "Voornaam",
                "PatientBirthDate": "19460701",
                "PatientGender": "F",
                "PatientLanguage": "FR",
                "PatientNN": "46000138467"
            },
            "PlanTime": "201602231300",
            "PlanTargetLocation": {
                "Campus": "001",
                "Ward": "2101",
                "Room": "207",
                "Bed": "01"
            },
            "AmbulatoryStatus": ""
        }}


+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body
    
            {
                "AortaOutMBResponse": "Received"
            }
            
            
## Stock Collection [/api/stocks]

## Patient Appointments Collection [/api/appointments]

## Tasks Collection [/api/tasks]