FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# AORTA Message Broker Sending Messages

Aorta Rest is a simple API allowing tasks to be routed and medical messages to be transferred.

List of services that will be called on remote applications:

 - Process Request - Task Management Application
   - Create a Process Request           POST   http://aorta:8441/api/processrequests/aeb7d11b-5588-4de7-822e-bd4a94da4df7
   - Delete a Process Request           DELETE http://aorta:8441/api/processrequests/aeb7d11b-5588-4de7-822e-bd4a94da4df7
   - Update a Process Request           PUT    http://aorta:8441/api/processrequests/aeb7d11b-5588-4de7-822e-bd4a94da4df7

 - Tasks - Dynamic Scheduling Application
   - Create a Task                      POST   http://aorta-api:8311/api/tasks/aeb7d11b-5588-4de7-822e-bd4a94da4df7
   - Delete a Task                      DELETE http://aorta-api:8311/api/tasks/aeb7d11b-5588-4de7-822e-bd4a94da4df7
   - Update a Task                      PUT    http://aorta-api:8311/api/tasks/aeb7d11b-5588-4de7-822e-bd4a94da4df7

## Process Requests Collection [/api/processrequests]

The collection of messages that deals with Process Requests.
Process Requests are used as input to create one or multiple tasks.

**POST requests**
 - First POST request: This message creates a process request.

**POST responses**
 - First POST response: HTTP 1/1 200 OK or any other HTTP Status Code 2xx. AortaMessageBroker will consider the message correctly treated and move to the next message.
 - Second POST response: HTTP 1/1 400 Bad Request, with specific body (see below). AortaMessageBroker will then discard the message from the FIFO to that receiver.
 - All other POST responses: AortaMessagebroker will keep repeating the same message (with configurable interval).

**DELETE requests**
 - First DELETE request: This message deletes a process request.

**PUT requests**
 - First PUT request: This message updates a process request.

### Create a Process Request [POST]

+ Request (application/json)

    + Body
    
            {
                "processId": "aeb7d11b-5588-4de7-822e-bd4a94da4df7",
                "type": "ProcessRequest",
                "description": "Pick up Patient X",
                "taskState": "Requested",
                "creationTime": "2016-03-10T12:34:56.123Z",
                "creator": "Task Manager",
                "taskType": "PatientTransport",
                "priority": "Normal",
                "transportMode": "Rolstoel",
                "transportType": "Terug",
                "processLinks": [{
                    "nextProcessId": "7278b5d1-afb8-4f4b-8141-615dd283c5d4"
                }],
                "personObjects": [{
                    "personId": "24a87862-0e8d-4e5e-8740-da1c818d843f",
                    "identificationMethods": [
                        { "identificationMethod": "OazisPatientId", "identificationKey": "12345678" },
                        { "identificationMethod": "NFC", "identificationKey": "fabdfa2b-16e8-455b-8b60-6b2ea5bffbde" }
                    ],
                    "firstName": "Goedele",
                    "lastName": "Bruynooghe",
                    "birthDate": "1961-05-21",
                    "gender": "V",
                    "location": {
                        "locationId": "2.W01.15a",
                        "name": "The red one",
                        "description": "Wachtruimte NKO"
                    },
                    "roles": ["Patient"]
                }],
                "proposedArrivalTime": "2016-03-11T13:30:00.000Z",
                "proposedArrivalTimeWindow": {
                    "timeWindowStart": "2016-03-11T13:30:00.000Z",
                    "timeWindowEnd": "2016-03-11T13:50:00.000Z"
                },
                "startLocation": {
                    "locationId": "2.W01.15a",
                    "description": "The red one",
                    "name": "Wachtruimte NKO"
                },
                "endLocation": {
                    "locationId": "1.W01.17a",
                    "description": "The blue one",
                    "name": "ReceptionBooth1"
                },
                "tasks": [{
                    "taskId": "76f8f381-4dd6-4e1d-a591-8a4d49ac0bce"
                }]
            }
            
    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-04/schema#",

                "definitions": {
                    "type": {
                        "type": "string",
                        "enum": [ "ProcessRequest", "Task", "Action" ]
                    },
                    "guidId": {
                        "type": "string",
                        "pattern": "[0-9A-Fa-f]{8}[-]?([0-9A-Fa-f]{4}[-]?){3}[0-9A-Fa-f]{12}"
                    },
                    "millisecondTimestampZ": {
                        "type": "string",
                        "pattern": "[12][0-9]{3}-[01][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{3}Z"
                    },
                    "yearsToSecondsDuration": {
                        "type": "string",
                        "pattern": "P((([0-9]*.?[0-9]*)Y)?(([0-9]*.?[0-9]*)M)?(([0-9]*.?[0-9]*)W)?(([0-9]*.?[0-9]*)D)?)?(T(([0-9]*.?[0-9]*)H)?(([0-9]*.?[0-9]*)M)?(([0-9]*.?[0-9]*)S)?)?"
                    },
                    "millisecondTimeWindowZ": {
                        "type": "object",
                        "properties": {
                            "timeWindowStart": { "ref": "#/definitions/millisecondTimestampZ" },
                            "timeWindowEnd": { "ref": "#/definitions/millisecondTimestampZ" }
                        }
                    },
                    "dateOnly": {
                        "type": "string",
                        "pattern": "[12][0-9]{3}-[01][0-9]-[0-3][0-9]"
                    },
                    "gender": {
                        "type": "string",
                        "enum": [ "M", "V", "F", "O", "U" ]
                    },
                    "coordinates": {
                        "type": "string",
                        "pattern": "[0-9].[a-zA-Z]?[a-zA-Z][0-9][0-9].[0-9][0-9][a-z]?"
                    },
                    "location": {
                        "type": "object",
                        "properties": {
                            "locationId": { "$ref": "#/definitions/coordinates" },
                            "name": { "type": "string" },
                            "description": { "type": "string" },
                            "coordinates": { "type": "string" }
                        },
                        "required": ["locationId"]
                    },
                    "creator": {
                        "type": "string",
                        "enum": [ "Aorta Message Broker", "Task Manager", "Notification Engine", "Context Engine", "Scheduling Application", "Wearable" ]
                    },
                    "taskState": {
                        "type": "string",
                        "enum": [ "Requested", "ToSchedule", "Scheduled", "Assigned", "Notified", "Accepted", "InProgress", "Refused", "Timeout", "Unreachable", "Interrupted", "Delayed", "Finished", "Cancelled" ]
                    },
                    "priority": {
                        "type": "string",
                        "enum": [ "Urgent", "High", "Normal", "Low" ]
                    },
                    "taskType": {
                        "type": "string",
                        "enum": [ "PatientTransport", "GoodsTransport" ]
                    },
                    "taskMode": {
                        "type": "string",
                        "enum": ["Afroep", "Herhalend"]
                    },
                    "transportType": {
                        "type": "string",
                        "enum": ["Enkel", "Heen", "Terug"]
                    },
                    "transportMode": {
                        "type": "string",
                        "enum": ["TeVoet", "Rolstoel", "Bed"]
                    },
                    "role": {
                        "type": "string",
                        "enum": [ "Nurse", "Doctor", "Patient", "Technician", "Logistics", "Administrative" ]
                    },
                    "identificationMethod": {
                        "type": "object",
                        "properties": {
                            "identificationMethod": { "type": "string", "enum": [ "OazisPatientId", "NFC" ] },
                            "identificationKey": { "type": "string" }
                        },
                        "required": [ "identificationMethod", "identificationKey" ]
                    },
                    "person": {
                        "type": "object",
                        "properties": {
                            "personId": { "$ref": "#/definitions/guidId" },
                            "firstName": { "type": "string" },
                            "lastName": { "type": "string" },
                            "birthDate": { "$ref": "#/definitions/dateOnly" },
                            "gender": { "$ref": "#/definitions/gender" },
                            "identificationMethods": { "type": "array", "items": {"$ref": "#/definitions/identificationMethod"} },
                            "location": { "$ref": "#/definitions/location" },
                            "roles": { "type": "array", "items": { "$ref": "#/definitions/role" } },
                            "competences": { "type": "array", "items": { "$ref": "#/definitions/competence" } },
                            "isActive": { "type": "boolean" },
                            "actionOptions": {}
                        },
                        "anyOf" : [
                            { "required" : [ "personId", "firstName", "lastName", "birthDate", "gender" ] },
                            { "required" : [ "personId", "identificationMethods" ] }
                        ]
                    },
                    "processLinks": {
                        "type": "object",
                        "properties": {
                            "nextProcessId": { "$ref": "#/definitions/guidId" },
                            "previousProcessId": { "$ref": "#/definitions/guidId" },
                            "requiredPreviousProcessState": { "$ref": "#/definitions/taskState" }
                        },
                        "anyOf" : [
                            { "required" : [ "nextProcessId" ] },
                            { "required" : [ "previousProcessId" ] }
                        ]
                    },
                    "preconditionState": {
                        "type": "string",
                        "enum": [ "Todo", "Done", "Achieved" ]
                    },
                    "precondition": {
                        "type": "object",
                        "properties": {
                            "preconditionId": { "$ref": "#/definitions/guidId" },
                            "description": { "type": "string" },
                            "preconditionState": { "$ref": "#/definitions/preconditionState" }
                        },
                        "required" : [ "preconditionId" ]
                    },
                    "task": {
                        "type": "object",
                        "properties": {
                            "taskId": { "$ref": "#/definitions/guidId" }
                        }
                    }
                },

                "type": "object",
                "required": [ "processId", "type", "taskState", "taskType" ],
                "properties": {
                    "processId": { "$ref": "#/definitions/guidId" },
                    "type": { "$ref": "#/definitions/type" },
                    "description": { "type": "string" },
                    "taskState": { "$ref": "#/definitions/taskState"},
                    "creationTime": { "$ref": "#/definitions/millisecondTimestampZ" },
                    "creator": { "$ref": "#/definitions/creator" },
                    "taskType": { "$ref": "#/definitions/taskType" },
                    "priority": { "$ref": "#/definitions/priority"},
                    "taskMode": { "$ref": "#/definitions/taskMode"},
                    "taskCanStart": { "type": "boolean" },
                    "transportMode": { "$ref": "#/definitions/transportMode" },
                    "transportType": { "$ref": "#/definitions/transportType" },
                    "processLinks": { "type": "array", "items": {"$ref": "#/definitions/processLinks"} },
                    "personObjects": { "type": "array", "items": {"$ref": "#/definitions/person"} },
                    "proposedDepartureTime": { "$ref": "#/definitions/millisecondTimestampZ" },
                    "proposedDepartureTimeWindow": { "$ref": "#/definitions/millisecondTimeWindowZ" },
                    "proposedArrivalTime": { "$ref": "#/definitions/millisecondTimestampZ" },
                    "proposedArrivalTimeWindow": { "$ref": "#/definitions/millisecondTimeWindowZ" },
                    "proposedRecurringInterval": { "$ref": "#/definitions/yearsToSecondsDuration" },
                    "startLocation": { "$ref": "#/definitions/location" },
                    "endLocation": { "$ref": "#/definitions/location" },
                    "responseDeadline": { "$ref": "#/definitions/millisecondTimestampZ" },
                    "preconditions": { "type": "array", "items": {"$ref": "#/definitions/precondition"} },
                    "tasks": { "type": "array", "items": {"$ref": "#/definitions/task"} }
                }
            }

+ Response 200 (application/json)

+ Response 400 (application/json)

    + Body
    
            {
                "AortaMessageBrokerOutputResponse": "Rejected"
            }

### Delete a Process Request [DELETE]

+ Response 200 (application/json)

+ Response 400 (application/json)

    + Body
        
            {
                "AortaMessageBrokerOutputResponse": "Rejected"
            }

### Update a Process Request [PUT]

+ Response 200 (application/json)

+ Response 400 (application/json)

    + Body
    
            {
                "AortaMessageBrokerOutputResponse": "Rejected"
            }

## Tasks Collection [/api/tasks]

The collection of messages that deals with Tasks.
Tasks contain actions that need to be performed by a person.

**POST requests**
 - First POST request: This message creates a task.

**POST responses**
 - First POST response: HTTP 1/1 200 OK or any other HTTP Status Code 2xx. AortaMessageBroker will consider the message correctly treated and move to the next message.
 - Second POST response: HTTP 1/1 400 Bad Request, with specific body (see below). AortaMessageBroker will then discard the message from the FIFO to that receiver.
 - All other POST responses: AortaMessagebroker will keep repeating the same message (with configurable interval).

**DELETE requests**
 - First DELETE request: This message deletes a task.

**PUT requests**
 - First PUT request: This message updates a task.

### Create a Task [POST]

+ Request (application/json)

    + Body
    
            {
                "taskId": "6b73b7cc-1221-44ad-93cb-38f4732350b5",
                "processId": "aeb7d11b-5588-4de7-822e-bd4a94da4df7",
                "creationTime": "2016-05-25T15:11:32.366Z",
                "creator": "Scheduling Application",
                "taskType": "PatientTransport",
                "subject": {
                    "personId": "00000000-0000-0000-0000-000000000203",
                    "identificationMethods": [{
                        "identificationMethodId" : "24a87862-0e8d-4e5e-8740-da1c818d843d",
                        "type": "NFC",
                        "value":"1234"
                    }],
                    "firstName": "Jan",
                    "lastName": "Janssens",
                    "birthDate": "2016-05-25T00:00:00.000Z",
                    "location": {
                        "locationId": "0.N92.09",
                        "name": "0.N92.09",
                        "description" : "http://aorta.intec.ugent.be/ontology/aorta.owl#Elevator",
                        "coordinates" : "0--4984"
                    },
                    "roles": ["Nurse"],
                    "competences": ["CareTransport", "LogisticTransport"],
                    "isActive": true
                },
                "startLocation": {
                    "locationId": "0.N92.09",
                    "name": "0.N92.09",
                    "description" : "http://aorta.intec.ugent.be/ontology/aorta.owl#Elevator",
                    "coordinates" : "0--4984"
                },
                "endLocation": {
                    "locationId": "0.N92.09",
                    "name": "0.N92.09",
                    "description" : "http://aorta.intec.ugent.be/ontology/aorta.owl#Elevator",
                    "coordinates" : "0--4984"
                },
                "responseDeadline": "2016-05-25T15:11:32.375Z",
                "actions": [{
                    "actionId": "9b8cd5c1-084c-4df0-a174-57bf54a718c0",
                    "actionType": "Pickup",
                    "actionOptions": [{ 
                        "actionOptionId" : "00000000-0000-0000-0000-000000000001",
                        "type" : "carrier",
                        "value" : "bed",
                        "description" : ""
                    },{
                        "actionOptionId":"00000000-0000-0000-0000-000000000002", 
                        "type" : "warning", 
                        "value" : "gloves", 
                        "description" : "Voorzorgsmaatregelen handschoenen"
                    }]
                    ,
                    "personObjects": [{
                        "personId": "24a87862-0e8d-4e5e-8740-da1c818d843f",
                        "identificationMethods": [{
                            "identificationMethodId" : "24a87862-0e8d-4e5e-8740-da1c818d843d",
                            "type": "NFC",
                            "value":"1234"
                        }],
                        "firstName": "Person",
                        "lastName": "1",
                        "birthDate": "25/05/2016",
                        "location": {
                            "locationId": "0.N92.09",
                            "name": "0.N92.09",
                            "description" : "http://aorta.intec.ugent.be/ontology/aorta.owl#Elevator",
                            "coordinates" : "0--4984"
                        },
                        "roles": ["Patient"],
                    }],
                    "competences": [],
                    "isActive": true,           
                    "itemObjects": [{
                        "itemId": "2e8d0baf-237d-4547-a473-b98fe15edc37",
                        "description": "Green Wheelchair",
                        "location": {
                            "locationId": "0.N92.09",
                            "name": "0.N92.09",
                            "description" : "http://aorta.intec.ugent.be/ontology/aorta.owl#Elevator",
                            "coordinates" : "0--4984"
                        },
                        "itemType": "Wheelchair",
                        "identificationMethods": [{
                            "identificationMethodId" : "24a87862-0e8d-4e5e-8740-da1c818d843d",
                            "type": "NFC",
                            "value":"1234"
                            }]
                    }],
                    "location": {
                        "locationId": "0.N92.09",
                        "name": "0.N92.09",
                        "description" : "http://aorta.intec.ugent.be/ontology/aorta.owl#Elevator",
                        "coordinates" : "0--4984"
                    },
                    "effectiveStartTime": "2016-05-25T15:11:32.382Z",
                    "effectiveEndTime": "2016-05-25T15:11:32.382Z",
                    "preconditions": [{
                        "preconditionId": "87e09b2f-c154-4310-a4f5-d3c676fb28be",
                        "description": "For this transport a wheelchair is needed"
                    }],
                    "description": "Pickup patient X",
                    "state": "busy"
                }],
                "state": "busy",
                "priority" : "High",
                "delayReason" : "",
                "delayDuration" : ""
            }

    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-04/schema#",

                "definitions": {
                    "type": {
                        "type": "string",
                        "enum": [ "ProcessRequest", "Task", "Action" ]
                    },
                    "guidId": {
                        "type": "string",
                        "pattern": "[0-9A-Fa-f]{8}[-]?([0-9A-Fa-f]{4}[-]?){3}[0-9A-Fa-f]{12}"
                    },
                    "millisecondTimestampZ": {
                        "type": "string",
                        "pattern": "[12][0-9]{3}-[01][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9].[0-9]{3}Z"
                    },
                    "yearsToSecondsDuration": {
                        "type": "string",
                        "pattern": "P((([0-9]*.?[0-9]*)Y)?(([0-9]*.?[0-9]*)M)?(([0-9]*.?[0-9]*)W)?(([0-9]*.?[0-9]*)D)?)?(T(([0-9]*.?[0-9]*)H)?(([0-9]*.?[0-9]*)M)?(([0-9]*.?[0-9]*)S)?)?"
                    },
                    "millisecondTimeWindowZ": {
                        "type": "object",
                        "properties": {
                            "timeWindowStart": { "ref": "#/definitions/millisecondTimestampZ" },
                            "timeWindowEnd": { "ref": "#/definitions/millisecondTimestampZ" }
                        }
                    },
                    "dateOnly": {
                        "type": "string",
                        "pattern": "[12][0-9]{3}-[01][0-9]-[0-3][0-9]"
                    },
                    "gender": {
                        "type": "string",
                        "enum": [ "M", "V", "F", "O", "U" ]
                    },
                    "coordinates": {
                        "type": "string",
                        "pattern": "[0-9].[a-zA-Z]?[a-zA-Z][0-9][0-9].[0-9][0-9][a-z]?"
                    },
                    "location": {
                        "type": "object",
                        "properties": {
                            "locationId": { "$ref": "#/definitions/coordinates" },
                            "name": { "type": "string" },
                            "description": { "type": "string" },
                            "coordinates": { "type": "string" }
                        },
                        "required": [ "locationId" ]
                    },
                    "creator": {
                        "type": "string",
                        "enum": [ "Aorta Message Broker", "Task Manager", "Notification Engine", "Context Engine", "Scheduling Application", "Wearable" ]
                    },
                    "taskState": {
                        "type": "string",
                        "enum": [ "Requested", "ToSchedule", "Scheduled", "Assigned", "Notified", "Accepted", "InProgress", "Refused", "Timeout", "Unreachable", "Interrupted", "Delayed", "Finished", "Cancelled" ]
                    },
                    "priority": {
                        "type": "string",
                        "enum": [ "Urgent", "High", "Normal", "Low" ]
                    },
                    "taskType": {
                        "type": "string",
                        "enum": [ "PatientTransport", "GoodsTransport" ]
                    },
                    "role": {
                        "type": "string",
                        "enum": [ "Nurse", "Doctor", "Patient", "Technician", "Logistics", "Administrative" ]
                    },
                    "identificationMethod": {
                        "type": "object",
                        "properties": {
                            "identificationMethodId": { "$ref": "#/definitions/guidId" },
                            "type": { "type": "string", "enum": [ "OazisPatientId", "NFC" ] },
                            "value": { "type": "string" }
                        },
                        "required": [ "identificationMethodId", "type" ]
                    },
                    "person": {
                        "type": "object",
                        "properties": {
                            "personId": { "$ref": "#/definitions/guidId" },
                            "firstName": { "type": "string" },
                            "lastName": { "type": "string" },
                            "birthDate": { "$ref": "#/definitions/millisecondTimestampZ" },
                            "gender": { "$ref": "#/definitions/gender" },
                            "identificationMethods": { "type": "array", "items": {"$ref": "#/definitions/identificationMethod"} },
                            "location": { "$ref": "#/definitions/location" },
                            "roles": { "type": "array", "items": { "$ref": "#/definitions/role" } },
                            "competences": { "type": "array", "items": { "$ref": "#/definitions/competence" } },
                            "isActive": { "type": "boolean" },
                            "actionOptions": {}
                        },
                        "anyOf" : [
                            { "required" : [ "personId", "firstName", "lastName", "birthDate", "gender" ] },
                            { "required" : [ "personId", "identificationMethods" ] }
                        ]
                    },
                    "processLinks": {
                        "type": "object",
                        "properties": {
                            "nextProcessId": { "$ref": "#/definitions/guidId" },
                            "previousProcessId": { "$ref": "#/definitions/guidId" },
                            "requiredPreviousProcessState": { "$ref": "#/definitions/taskState" }
                        },
                        "anyOf" : [
                            { "required" : [ "nextProcessId" ] },
                            { "required" : [ "previousProcessId" ] }
                        ]
                    },
                    "preconditionState": {
                        "type": "string",
                        "enum": [ "Todo", "Done", "Achieved" ]
                    },
                    "precondition": {
                        "type": "object",
                        "properties": {
                            "preconditionId": { "$ref": "#/definitions/guidId" },
                            "description": { "type": "string" },
                            "preconditionState": { "$ref": "#/definitions/preconditionState" }
                        },
                        "required" : [ "preconditionId" ]
                    },
                    "task": {
                        "type": "object",
                        "properties": {
                            "taskId": { "$ref": "#/definitions/guidId" }
                        }
                    },
                    "competence": {
                        "type": "string",
                        "enum": [ "CareTransport", "LogisticTransport" ]
                    },
                    "deviceType": {
                        "type": "string",
                        "enum": [ "Smart watch" ]
                    },
                    "device": {
                        "type": "object",
                        "properties": {
                            "deviceId": { "$ref": "#/definitions/guidId" },
                            "description": { "type": "string" },
                            "identificationMethods": { "type": "array", "items": {"$ref": "#/definitions/identificationMethod"} },
                            "location": { "$ref": "#/definitions/location" },
                            "deviceType": { "$ref": "#/definitions/deviceType" }
                        },
                        "required" : [ "deviceId", "identificationMethods" ]
                    },
                    "itemType": {
                        "type": "string",
                        "enum": [ "Wheelchair" ]
                    },
                    "item": {
                        "type": "object",
                        "properties": {
                            "itemId": { "$ref": "#/definitions/guidId" },
                            "description": { "type": "string" },
                            "identificationMethods": { "type": "array", "items": {"$ref": "#/definitions/identificationMethod"} },
                            "location": { "$ref": "#/definitions/location" },
                            "itemType": { "$ref": "#/definitions/itemType" }
                        },
                        "required" : [ "itemId", "identificationMethods" ]
                    },
                    "action": {
                        "type": "object",
                        "properties": {
                            "actionId": { "$ref": "#/definitions/guidId" }
                        }
                    }
                },

                "type": "object",
                "required": [ "taskId", "type", "processId", "taskState", "taskType" ],
                "properties": {
                    "taskId": { "$ref": "#/definitions/guidId" },
                    "processId": { "$ref": "#/definitions/guidId" },
                    "type": { "$ref": "#/definitions/type" },
                    "description": { "type": "string" },
                    "taskState": { "$ref": "#/definitions/taskState"},
                    "creationTime": { "$ref": "#/definitions/millisecondTimestampZ" },
                    "creator": { "$ref": "#/definitions/creator" },
                    "taskType": { "$ref": "#/definitions/taskType" },
                    "priority": { "$ref": "#/definitions/priority"},
                    "taskMode": { "$ref": "#/definitions/taskMode"},
                    "subject": { "$ref": "#/definitions/person" },
                    "personObjects": { "type": "array", "items": {"$ref": "#/definitions/person"} },
                    "itemObjects": { "type": "array", "items": {"$ref": "#/definitions/item"} },
                    "startLocation": { "$ref": "#/definitions/location" },
                    "endLocation": { "$ref": "#/definitions/location" },
                    "responseDeadline": { "$ref": "#/definitions/millisecondTimestampZ" },
                    "preconditions": { "type": "array", "items": {"$ref": "#/definitions/precondition"} },
                    "actions": { "type": "array", "items": {"$ref": "#/definitions/action"} },
                    "delayDuration": { "type": "string" },
                    "delayReason": { "type": "string" },
                }
            }
        
+ Response 200 (application/json)

+ Response 400 (application/json)

    + Body
    
            {
                "AortaMessageBrokerOutputResponse": "Rejected"
            }

### Delete a Task [DELETE]

+ Response 200 (application/json)

+ Response 400 (application/json)

    + Body
    
            {
                "AortaMessageBrokerOutputResponse": "Rejected"
            }

### Update a Task [PUT]

+ Response 200 (application/json)

+ Response 400 (application/json)

    + Body
    
            {
                "AortaMessageBrokerOutputResponse": "Rejected"
            }